presentation/Store.Wen/Models/Cart.cs
namespace Store.Wen.Models
{
    public class Cart
    {
        public IDictionary<int, int> Items { get; set; } = new Dictionary<int, int>();

        public decimal Amount { get; set; } 
    }
}

presentation/Store.Wen/Models/ErrorViewModel.cs
namespace Store.Wen.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

presentation/Store.Wen/Controllers/BookController.cs
using Microsoft.AspNetCore.Mvc;

namespace Store.Wen.Controllers
{
    public class BookController : Controller
    {
        private readonly IBookRepository bookRepository;

        public BookController(IBookRepository bookRepository)
        {
            this.bookRepository = bookRepository;
        }

        public IActionResult Index(int id)
        {
            Book book = bookRepository.GetById(id);

            return View(book);
        }
    }
}

presentation/Store.Wen/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using Store.Wen.Models;

namespace Store.Wen.Controllers
{
    public class CartController : Controller
    {
        private readonly IBookRepository bookRepository;

        public CartController(IBookRepository bookRepository)
        {
            this.bookRepository = bookRepository;
        }

        public IActionResult Add(int id)
        {
            var book = bookRepository.GetById(id);
            Cart cart;
            if (!HttpContext.Session.TryGetCart(out cart))
                cart = new Cart();

            if (cart.Items.ContainsKey(id))
                cart.Items[id]++;
            else
                cart.Items[id] = 1;

            cart.Amount += book.Price;

            HttpContext.Session.Set(cart);

            return RedirectToAction("Index", "Book", new { id });
        }
    }
}

presentation/Store.Wen/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Store.Wen.Models;
using System.Diagnostics;

namespace Store.Wen.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

presentation/Store.Wen/Controllers/SearchController.cs
using Microsoft.AspNetCore.Mvc;

namespace Store.Wen.Controllers
{
    public class SearchController : Controller
    {
        private readonly BookService bookService;

        public SearchController(BookService bookService)
        {
            this.bookService = bookService;
        }
        public IActionResult Index(string query)
        {

            var books = bookService.GetAllByQuery(query);

            return View(books);
        }
    }
}

presentation/Store.Wen/Views/Book/Index.cshtml
@model Book

@{
    ViewData["Title"] = Model.Title;
}

<h1>@Model.Title</h1>
<p><strong>@Model.Author</strong></p>
<p>@Model.Description</p>
<p>Цена: <strong>@Model.Price</strong>$</p>
<form action="@Url.Action("Add", "Cart")" method="post">
    <input type="hidden" name="id" value="@Model.Id"/>
    <button class="btn btn-outline-success" type="submit">В корзину</button>
</form>

presentation/Store.Wen/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

presentation/Store.Wen/Views/Search/Index.cshtml
@model Book[]

@{
    ViewData["Title"] = "Результаты поиска";
}

<h1>Результаты поиска</h1>

@if (Model.Length == 0)
{
    <p>Ничего не найдено.</p>
}
else 
{
    <ul>
        @foreach (var book in Model)
        {
            <li><a href="@Url.Action("Index", "Book", new { id = book.Id})">@book.Title</a></li>
        }
    </ul>
}

presentation/Store.Wen/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Библиотечная</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Store.Wen.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-light bg-light justify-content-between">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"> IIIопстайл </a>
            <form class="form-inline my-2 my-lg-0  d-flex" action="@Url.Action("Index", "Search")" method="get">
                <input class="form-control mr-sm-2" type="search" name="query" placeholder="Автор или название"/>
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Искать</button>
            </form>
            <span class="navbar-text m-lg-auto">
                @{
                    Cart cart;
                    if (!Context.Session.TryGetCart(out cart))
                        cart = new Cart();

                    if (cart.Items.Count == 0)
                    {
                        @:Корзина пуста
                    }
                    else
                    {
                        @:Товаров @cart.Items.Count на сумму @cart.Amount
                    }
                }
            </span>
        </nav>
    </header>
    <div class="container">
        <main>
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>